name: Docker Image CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/llmrl:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx (docker-container driver)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          # optional but fine:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE }}
          # GHA-backed cache
          cache-from: type=gha,scope=llmrl
          cache-to: type=gha,mode=max,scope=llmrl
